### ISSUE TITLE
Illegal instruction on Raspberry Pi

### ISSUE THREAD

**Issue by coolnickname** [xarantolus/upduck#3]
I'm using the raspberry pi version and all it says is "Illegal instruction".

```
pi@raspberrypi:~/ducky-weather/upduck $ sudo ./upduck-raspberrypi -h
Illegal instruction
pi@raspberrypi:~/ducky-weather/upduck $ neofetch
  `.::///+:/-.        --///+//-:``    pi@raspberrypi 
 `+oooooooooooo:   `+oooooooooooo:    -------------- 
  /oooo++//ooooo:  ooooo+//+ooooo.    OS: Raspbian GNU/Linux 10 (buster) armv6l 
  `+ooooooo:-:oo-  +o+::/ooooooo:     Host: Raspberry Pi Zero W Rev 1.1 
   `:oooooooo+``    `.oooooooo+-      Kernel: 4.19.118+ 
     `:++ooo/.        :+ooo+/.`       Uptime: 13 days, 23 hours, 16 mins 
        ...`  `.----.` ``..           Packages: 572 (dpkg) 
     .::::-``:::::::::.`-:::-`        Shell: bash 5.0.3 
    -:::-`   .:::::::-`  `-:::-       Terminal: /dev/pts/0 
   `::.  `.--.`  `` `.---.``.::`      CPU: BCM2835 (1) @ 1.000GHz 
       .::::::::`  -::::::::` `       Memory: 62MiB / 432MiB 
 .::` .:::::::::- `::::::::::``::.
-:::` ::::::::::.  ::::::::::.`:::-                           
::::  -::::::::.   `-::::::::  ::::
-::-   .-:::-.``....``.-::-.   -::-
 .. ``       .::::::::.     `..`..
   -:::-`   -::::::::::`  .:::::`
   :::::::` -::::::::::` :::::::.
   .:::::::  -::::::::. ::::::::
    `-:::::`   ..--.`   ::::::.
      `...`  `...--..`  `...`
            .::::::::::
             `.-::::-`


```

**Comment by xarantolus** [comment]
Ah, that's interesting.

I think this happens because it is [compiled](https://github.com/xarantolus/upduck/blob/cdfde597b63033f0fef9cd1297d268dadfc18b1b/release.sh#L10) with `GOARM=7` and your Raspberry Pi supports `armv6l`.

I compiled two new versions (one with `GOARM=5` and the other one with `GOARM=6`) and put them into a [zip](https://github.com/xarantolus/upduck/files/4977970/upduck.zip) file, it would be interesting to see if they work (both should).

Compile commands:

    GOOS=linux GOARCH=arm GOARM=5 go build -o upduck-raspberrypi-arm5
    GOOS=linux GOARCH=arm GOARM=6 go build -o upduck-raspberrypi-arm6

So the solution to this -- if it works -- would be changing the compile command to ARMv5 in the build script to make sure all Raspberry Pis are supported.

Thanks for your report :)

**Comment by coolnickname** [comment]
They indeed both work. Thanks for your support!
