### ISSUE TITLE
[Feature Request] Optional user authentication

### ISSUE THREAD

**Issue by Darthagnon** [xarantolus/upduck#4]
Would please be possible to implement user authentication to access files? e.g. set some usernames and passwords in the config and prompt for authentication before listing/file access is allowed. 

Would also be really nice if the ```HTTP server starting on port 8080``` prompt included the IP address that the port was opened on - makes it easier, e.g. if running a server temporarily to share files with friends, to be able to more easily tell them what IP and port to connect to.

This project looks very promising! Thank you for making it!

**Comment by Darthagnon** [comment]
I just discovered this project: https://github.com/codeskyblue/gohttpserver/releases/ - fully featured Go-based MFT server, with authentication.

**Comment by xarantolus** [comment]
I really like the idea of user accounts so I implemented it :) 

> if running a server temporarily to share files with friends, to be able to more easily tell them what IP and port to connect to.

That's a bit hard (but would be very nice) because the program doesn't know which port was forwarded in the router (could make that a setting, I guess). Displaying the public IP address might be possible, but I don't think it's more useful than the duckdns domain name. Since both need the port to display the correct URL both don't work as long as we cannot get that. 

You can reopen the issue if you want to, I forgot the quoted part at first.

**Comment by Darthagnon** [comment]
Thank you so much for implementing authentication and IP showing!

Noticed it now displays index.html - does it have to be a basic one, or can it be any index.html with dependent CSS/JS?

**Comment by xarantolus** [comment]
It can be any index.html, I just added it because usually all webservers show the index file if it exists instead of showing the directory listing. It is possible to link/embed other resources as long as the correct path (usually relative) is given, just with any other server. There should be no difference between serving an html page with this server and any others

**Comment by Darthagnon** [comment]
Wondering, RE: index.html - are there some exposed identifiers for  folder-up, buttons, list view, etc. within upduck that could be targeted? I tested the index.html (plus stuff) from the [codeskyblue project](https://github.com/codeskyblue/gohttpserver/releases/), and it loaded, though it was kinda broken, as that one I believe implements a lot of server-specific code.

I'm wondering if e.g. an index.html (+CSS+JS) could be used as a "skin"/theme for upduck's file list view. Idea: what if an index.html (plus content) placed next to upduck.exe (and/or in .config) were applied to every directory listing page (except where another index.html is present)? This would enable some sort of universal skinning system.

**Comment by xarantolus** [comment]
> I'm wondering if e.g. an index.html (+CSS+JS) could be used as a "skin"/theme for upduck's file list view

It's definitely possible, but I honestly don't feel like implementing it right now. You can however modify `templateText` in `server.go` if you want to change something (requires recompiling though)
